### ISSUE TITLE
Support LTC codegen for PyTorch/XLA

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#3472]
## 🚀 Feature
Replace PyTorch/XLA's existing op lowering code structure with the lTC code gen

## Motivation
1. Clean up the stub code we have to copy paste for each lowering
2. Get Meta tensor output shape inference for PyTorch/XLA(useful for Dynamic shape)
3. Reduce the cost for later LazyTensor class migration.

FYI @wconstab @wonjoolee95 @miladm

**Comment by JackCaoG** [comment]
I am able to see some output using the code gen, what I did was 
1. Create a `gen.py` file under `pytorch`(this is a workaround we need to fix later)

```
from tools.codegen.gen_lazy_tensor import run_gen_lazy_tensor

run_gen_lazy_tensor(aten_path="aten/src/ATen",
                    source_yaml="xla/xla_native_functions.yaml",
                    backend_name="XLA",
                    output_dir="xla/torch_xla/csrc/generated",
                    dry_run=False,
                    impl_path="xla/torch_xla/csrc/aten_xla_type.cpp",
                    gen_ts_lowerings=False,
                    node_base="Node",
                    node_base_hdr="xla/torch_xla/csrc/ir.h",
                    build_in_tree=True,
                    per_operator_headers=True)
```

This code is modified from ltc version in https://github.com/pytorch/pytorch/blob/b9e535a64a98e24d1c0e18dcffaabe9879845386/tools/setup_helpers/generate_code.py#L200

What I ended up are 5 files
```
(pytorch2) jackcao@jackcao64:~/Desktop/gitProj2/pytorch/xla/torch_xla/csrc/generated$ ls
LazyIr.h                 RegisterXLA.cpp         XLANativeFunctions.h
RegisterAutogradXLA.cpp  XLANativeFunctions.cpp
```

**Comment by JackCaoG** [comment]
Let's go over the file one by one

`RegisterXLA.cpp` is something we already generated today, it is under `torch_xla/csrc`. Looking at the file, the new one is almost identical, which is expected since they call the same helper function.

The only difference is extra include in the newly generated file
```
#include <ATen/ops/as_strided_native.h>
#include <ATen/ops/empty.h>
#include <ATen/ops/empty_strided.h>
#include <ATen/ops/_copy_from_and_resize.h>
#include <ATen/ops/_copy_from.h>
```

I think it is something related to ts_backend and we should remove those.

`RegisterAutogradXLA.cpp`'s situation is very similar to `RegisterXLA.cpp`, the only meaningful difference is extra include. I can bring this up in the meeting so maybe we can clean it up.

**Comment by JackCaoG** [comment]
`LazyIr.h` reads `xla_native_functions.yaml`'s `full_codegen:` tab. If I didn't put anything there it is empty. I tried to add `abs` under this tab

```
backend: XLA
cpp_namespace: torch_xla
full_codegen:
  - abs
```

and now I am seeing
```
#pragma once

// This file contains autogenerated LazyTensor IR nodes
#include <ATen/core/Formatting.h>
#include <c10/core/ScalarType.h>
#include <c10/util/Optional.h>
#include <torch/csrc/lazy/core/hash.h>
#include <torch/csrc/lazy/core/ir.h>
#include <torch/csrc/lazy/core/shape.h>
#include <vector>
#include "xla/torch_xla/csrc/ir.h"

namespace torch {
namespace lazy {
using at::operator<<;

// kNullValue is used to contribute a static hash value any time
// a node has an Optional<Value> input that is nullopt.  It is important
// to differentiate between HASH(nullopt, something) and HASH(something, nullopt),
// and using kNullValue in the hash function in the order of arguments
// serves this purpose.
static const torch::lazy::Value kNullValue = torch::lazy::Value();

class Abs : public Node {
 public:
  Abs(const torch::lazy::Value& self, std::vector<Shape>&& shapes)
      : Node(torch::lazy::OpKind(at::aten::abs),
              {self}, std::move(shapes),
              /* num_outputs */ 1,
              torch::lazy::MHash())
        

  {
    
  }

  std::string ToString() const override {
    std::stringstream ss;
    ss << Node::ToString();
    
    return ss.str();
  }

  torch::lazy::TSOpVector Lower(std::shared_ptr<torch::jit::GraphFunction> function,
                   torch::lazy::TSLoweringContext* loctx) const override {
        std::vector<torch::jit::NamedValue> arguments;
    std::vector<torch::jit::NamedValue> kwarguments;
    arguments.reserve(1);
    kwarguments.reserve(0);
    size_t i = 0;
    arguments.emplace_back(loctx->GetOutputOp(operand(i++)));
    
    torch::lazy::TSOpVector abs_out = torch::lazy::LowerTSBuiltin(function, op().op, arguments, kwarguments);
    CHECK_EQ(abs_out.size(), 1);

    return abs_out;

  }

  
  

};

} // namespace lazy
} // namespace torch
```

couple things I noticed that is off
1. we need to fix the `#include "xla/torch_xla/csrc/ir.h"`, `xla` should not be included in the path
2. ideally namespace should be `torch_xla` instead of `torch::lazy`. I wonder in the long term if it is a good idea for pt/xla to totally migrate to `torch::lazy::nameapsce`. we might run into some small issues here and there
3. we need to rename `Node` to `XlaNode` to be more precise. 
4. I am guessing `std::vector<Shape>&& shapes` is the meta_kernel inferred shape. I think it is OK
5. We still need a way to plug in the `xla::Shape`. In the case of ABS it is ok since we know the output shape. In the more complicated case we need to a way to plug in the `shape_compuation_function` like we do today.
6. Lower function does not applied to PyTorch/XLA. We need to come up with something else.

**Comment by JackCaoG** [comment]
`XLANativeFunctions.h` is the same as what we have today, namespace is also correctly set to `torch_xla`.

`XLANativeFunctions.cpp` looks like

```
// @generated by tools/codegen/gen.py from DispatchKeyNativeFunctions.cpp
#include <torch/csrc/lazy/core/tensor.h>
#include <torch/csrc/lazy/core/shape_inference.h>
#include <ATen/Functions.h>
#include <ATen/MetaFunctions.h>
#include <ATen/Operators.h>
#include <ATen/native/CPUFallback.h>
#include <torch/csrc/lazy/core/lazy_graph_executor.h>
#include <torch/csrc/lazy/core/metrics.h>
#include <torch/csrc/lazy/core/shape.h>
#include <xla/torch_xla/csrc/generated/XLANativeFunctions.h>
#include <xla/torch_xla/csrc/generated/LazyIr.h>
#include <torch/csrc/lazy/ts_backend/ts_eager_fallback.h>


namespace torch_xla {

    at::Tensor XLANativeFunctions::abs(const at::Tensor & self) {
        
        if (force_eager_fallback(at::aten::abs)) {
            return at::native::call_fallback_fn<&ltc_eager_fallback, ATEN_OP(abs)>::call(
                self
            );
        }

        TORCH_LAZY_FN_COUNTER("lazy::");
        auto common_device = torch::lazy::GetBackendDevice(self);
        TORCH_INTERNAL_ASSERT(common_device);
        
        torch::lazy::LazyTensorPtr lazy_self = torch::lazy::GetLtcTensorOrCreateForWrappedNumber(self, *common_device);
        
        auto shapes = torch::lazy::compute_shape_abs(self);
        TORCH_INTERNAL_ASSERT(shapes.size() == 1);
        auto node = torch::lazy::MakeNode<Abs>(lazy_self->GetIrValue(),
                                                                                      std::move(shapes));
        auto result = torch::lazy::CreateAtenFromLtcTensor(
                torch::lazy::LazyTensor::Create(std::move(node), *common_device));
        return result;
    };

} // namespace torch_xla
```

Couple things I notcied
1. We should get rid of `torch/csrc/lazy/ts_backend/ts_eager_fallback.h` and call to `force_eager_fallback`
2. We might need our metric header instead of the lazy one (at least for now), same for call to `TORCH_LAZY_FN_COUNTER`
3. I don't think we support `torch::lazy::GetBackendDevice` today
4. Need to use our version of `GetLtcTensorOrCreateForWrappedNumber`.. until we migrated to LTC fully
5. Need to use xla version of `CreateAtenFromLtcTensor` for now

**Comment by wconstab** [comment]
> Create a gen.py file under pytorch(this is a workaround we need to fix later)

You should be able to just directly invoke `gen_lazy_tensor.py` with cmd line args provided to argparse.  the `run_gen..` function was added to let us invoke it from other python scripts like the torch autograd codegen as part of the main torch build, but you shouldn't feel required to use that `run_` function.  If there are some argparse flags missing, we can add them.

**Comment by wconstab** [comment]
>                     node_base_hdr="xla/torch_xla/csrc/ir.h",

I thought you already moved to using ir.h Node base from ltc.

**Comment by wconstab** [comment]
>The only difference is extra include in the newly generated file
```

#include <ATen/ops/as_strided_native.h>
#include <ATen/ops/empty.h>
#include <ATen/ops/empty_strided.h>
#include <ATen/ops/_copy_from_and_resize.h>
#include <ATen/ops/_copy_from.h>
I think it is something related to ts_backend and we should remove those.
```

I think even xla is actually using these includes (e.g. copy_from).  You should have generated 'inplace' kernels that call functional kernels and use copy_from to set the result.

The reason for this change is that under some torch CI configs, we enforce one of 2 things
 - that specific ops/* files are included, but no global 'Functions.h' is included
 - that only 'Functions.h' is included, and no specific ops headers are included
 
So in order to run the codegen in more build configs, I had to make the codegen honor the cmake flag for 'per-operator-headers'.  I don't think it should be a problem for xla to use the per-operator includes in this case.  Even if there is a header there that is only needed by one backend, i would probably argue for keeping all backends using a super-set of needed headers here rather than build the logic somewhere to use different sets of headers per backend.  Wdyt?

**Comment by wconstab** [comment]
For the LazyIr.h file:

> couple things I noticed that are off
> 
> 1. we need to fix the #include "xla/torch_xla/csrc/ir.h", xla should not be included in the path
> 3. we need to rename Node to XlaNode to be more precise.

I think these 2 would both be fixed if you change the parameters you pass to the codegen, although I'm not clear which direction you want to go.  If you want to change from Node to XlaNode, then i think you must keep the xla/.../ir.h include.  Or if you want to get rid of the xla include, it would imply you want to use our 'Node' base right?
```
                    node_base="XlaNode",
                    node_base_hdr="xla/torch_xla/csrc/ir.h",
```


> 2. ideally namespace should be torch_xla instead of torch::lazy. I wonder in the long term if it is a good idea for pt/xla to totally migrate to torch::lazy::nameapsce. we might run into some small issues here and there

- [ ] @wconstab use codegen namespace param for ir 

> 4. I am guessing std::vector<Shape>&& shapes is the meta_kernel inferred shape. I think it is OK

Yep

> 5. We still need a way to plug in the xla::Shape. In the case of ABS it is ok since we know the output shape. In the more complicated case we need to a way to plug in the shape_compuation_function like we do today.

Ok, this needs more discussion.  One option is that you deal with xla::Shape in the XlaNode base class, and it is hidden from the codegen'd IR code.  If that option doesn't work, then we'd need to come up with what behavior change you want in the codegen.

> 6. Lower function does not applied to PyTorch/XLA. We need to come up with something else.

- [ ] @wconstab fix generation of 'Lower' decl when ts_lowerings flag is false

**Comment by wconstab** [comment]
RE NativeFunctions.cpp

> Couple things I notcied
> 
> 1. We should get rid of torch/csrc/lazy/ts_backend/ts_eager_fallback.h and call to force_eager_fallback

If you are not ok keeping the force fallback option, which is mainly for debugging perf (might be useful for you?), we can make that an option to the codegen so that block of code is omitted.

- [ ] @wconstab make force fallback codegen optional

Should we share some part of fallback code at this time?  An idea is to separate ts_eager_fallback into 2 parts, one part is a simple stub in lazy/core which calls into a new backend_api 'fallback' function, then xla/ts both provide their own fallback through this backend API.  Does this sound ok?  Any other proposal?

- [ ] @wconstab make fallback part of backend API and remove ts specific header from codegen

> 2. We might need our metric header instead of the lazy one (at least for now), same for call to TORCH_LAZY_FN_COUNTER

- [ ] @wconstab make metric header and counter be parameters to codegen

> 3. I don't think we support torch::lazy::GetBackendDevice today

hmm. is it something that is trivial to support, or do we need to discuss the design a bit?

> 4. Need to use our version of GetLtcTensorOrCreateForWrappedNumber.. until we migrated to LTC fully
> 5. Need to use xla version of CreateAtenFromLtcTensor for now

- [ ] @wconstab make CreateAtenFromLtcTensor and GetLtcTensorOrCreateForWrappedNumber be parameters to codegen

**Comment by JackCaoG** [comment]
I felt like `full_codegen` might be too much for us right now as 
1. lower function generated for ltc is very different than what we need and we lack a `fall_back` method for lower
2. We still need to compute the `xla::shape` for each node which will be very awkward to support using existing code gen


I think we can partially using codegen by only generate current `aten_xla_type.cpp` to `XLANativeFunctions.cpp`. This is the most important part of the code gen we need today anyway. It will
1. unblock us from using meta tensor to compute the output shape
2. Clean up the XLATensor class for future `LazyTensor` subclassing

I will do more exploration toward this direction.

**Comment by JackCaoG** [comment]
Trying to run `gen_lazy_tensor.py` direcly but run into issue with relative import

```
Traceback (most recent call last):
  File "../tools/codegen/gen_lazy_tensor.py", line 16, in <module>
    from .gen_backend_stubs import (parse_backend_yaml, error_on_missing_kernels,
ModuleNotFoundError: No module named '__main__.gen_backend_stubs'; '__main__' is not a package
```

removing the `.` in import to workaround it for now.


now under the `pytorch/xla` repo I can run
```
python3 ../tools/codegen/gen_lazy_tensor.py --source_yaml xla_native_functions.yaml --backend_name XLA --output_dir torch_xla/csrc/generated --impl_path torch_xla/csrc/aten_xla_type.cpp --node_base Node --node_base_hdr torch_xla/csrc/ir.h --shape_inference_hdr "../torch/csrc/lazy/core/shape_inference.h"
```

I have to pass a relative path or absolute path for `shape_inference_hdr` otherwise it won't be able to find the shape inference file. However now in the generate `XLANativeFunctions.cpp` I am seeing
```
#include <../torch/csrc/lazy/core/shape_inference.h>
```

The issue is in https://github.com/pytorch/pytorch/blob/master/tools/codegen/gen_lazy_tensor.py#L313. I think we need to separate "path to find to file" and the "path to include as header". Former one can be a absolute path but latter one should always start with "torch/". @bdhirsh WDYT?

**Comment by JackCaoG** [comment]
now in the `XLANativeFunctions.cpp`, we have
```
        auto common_device = torch::lazy::GetBackendDevice(self);
        TORCH_INTERNAL_ASSERT(common_device);
```

filed https://github.com/pytorch/xla/issues/3490 to switch to use upstream `BackendDevice` directly.

we also need to have a xla version of 
```
        torch::lazy::LazyTensorPtr lazy_self = torch::lazy::GetLtcTensorOrCreateForWrappedNumber(self, *common_device);
```

which should be pretty easy.

Other outstanding item is we use a lot of `input.CreateFrom`. LTC uses `Create` directly. 
```
        auto result = torch::lazy::CreateAtenFromLtcTensor(
                torch::lazy::LazyTensor::Create(std::move(node), *common_device));
```

One of the difference is that `CreateFrom` calls `MaybeCastIrValue` which I think we should able to get rid of right now. Need to investigate.

**Comment by bdhirsh** [comment]
> Trying to run `gen_lazy_tensor.py` direcly but run into issue with relative import
> ...
> removing the `.` in import to workaround it for now.
> 

If that works, then sounds good :) You might also be able to run `python -m tools.codegen.gen_lazy_tensor`


> I have to pass a relative path or absolute path for `shape_inference_hdr` otherwise it won't be able to find the shape inference file. However now in the generate `XLANativeFunctions.cpp` I am seeing
> 
> ```
> #include <../torch/csrc/lazy/core/shape_inference.h>
> ```
> 
> The issue is in https://github.com/pytorch/pytorch/blob/master/tools/codegen/gen_lazy_tensor.py#L313. I think we need to separate "path to find to file" and the "path to include as header". Former one can be a absolute path but latter one should always start with "torch/". @bdhirsh WDYT?

Yep agreed, if we can arrange for the include to always start with `torch` then that sounds ideal.

**Comment by JackCaoG** [comment]
There are a couple of todo item on my ened
1. https://github.com/pytorch/xla/issues/3490 to use the upstream device. @wonjoolee95 is working on this
2. I need to introduce a pytorch/xla version of `GetLtcTensorOrCreateForWrappedNumber`
3. Make a way to codegen the IR or modify the existing node to take `lazy::shape`
4. Try to use `XLATensor::Create` instead of `XlaTensor::CreateFrom`

4 is a bit tricky. PyTorch/XLA create new node mostly using `XlaTensor::CreateFrom` today because it inherits the `logical_element_type` (which is "what pytorch think this tensor's type should be") from the input tensor if it is set in the input tensor. This is not very ideal as there is not guarantee that input node and output node will have the same `at::ScalarType`. In LTC we will have meta tensor to compute the output shape for us so ideally we should just get rid of `logical_element_type` entirelly. During this migration process, as a short term solution I should just init `logical_element_type` using the meta tensor output shape.

4 is also a bit blocked by the current shape cache moving from TsNode to Node base so I will do it last.

**Comment by wconstab** [comment]
> 1. https://github.com/pytorch/xla/issues/3490 to use the upstream device. @wonjoolee95 is working on this
> 2. I need to introduce a pytorch/xla version of GetLtcTensorOrCreateForWrappedNumber

1,2 both sgtm. 
> 3. Make a way to codegen the IR or modify the existing node to take lazy::shape
3a - a way to codegen the IR: meaning, the codegen needs to know how to
* derive from XlaNode instead of TsNode (already possible)
* define a Lower method with XlaNode return type, and do NOT generate the lowering body (needs codegen change)
* customize XlaNode constructor call so it initializes Xla::Shape from lazy::Shape
* anything else?

3b- or modify the existing node to take lazy::shape
what do you mean by this?  Just add a XlaNode ctor that accepts lazy::shape and creates Xla::Shape internally?
 - I think you may want to do this part either way, and it helps with 3a.

> 4. Try to use XLATensor::Create instead of XlaTensor::CreateFrom

I agree it's better to ditch 'CreateFrom'.  But for migration purposes, if it is hard to do this, you could probably still customize codegen.  Codegen keeps track of 'first tensor' argument, so it could always emit some code like {first_tensor}.CreateFrom.  I don't prefer this way, but lmk if you want to try it and I can help.

Will try to land https://github.com/pytorch/pytorch/pull/75324 asap to unblock

**Comment by JackCaoG** [comment]
had a chat with @wconstab and we are aligned on the changes we need to make 

I generate below files with
```
from tools.codegen.gen_lazy_tensor import run_gen_lazy_tensor

run_gen_lazy_tensor(aten_path="aten/src/ATen",
                    source_yaml="xla/xla_native_functions.yaml",
                    backend_name="XLA",
                    output_dir="torch_xla/csrc/generated",
                    dry_run=False,
                    impl_path="torch_xla/csrc/aten_xla_type.cpp",
                    gen_ts_lowerings=False,
                    node_base="Node",
                    node_base_hdr="torch_xla/csrc/ir.h",
                    build_in_tree=True,
                    per_operator_headers=True)
```

in `XLANativeFunctions.cpp`, we currently have
```
// @generated by tools/codegen/gen.py from DispatchKeyNativeFunctions.cpp
#include <torch/csrc/lazy/core/tensor.h>
#include <../torch/csrc/lazy/core/shape_inference.h>
#include <ATen/Functions.h>
#include <ATen/MetaFunctions.h>
#include <ATen/Operators.h>
#include <ATen/native/CPUFallback.h>
#include <torch/csrc/lazy/core/lazy_graph_executor.h>
#include <torch/csrc/lazy/core/metrics.h>
#include <torch/csrc/lazy/core/shape.h>
#include <torch_xla/csrc/generated/XLANativeFunctions.h>
#include <torch_xla/csrc/generated/LazyIr.h>


namespace torch_xla {

    at::Tensor XLANativeFunctions::abs(const at::Tensor & self) {
      // let xla plug in counter macro
        XLA_FN_COUNTER("xla::");
        // pt/xla have a pr pending
        auto common_device = torch::lazy::GetBackendDevice(self);
        TORCH_INTERNAL_ASSERT(common_device);

        // pt/xla need to implmenet GetLtcTensorOrCreateForWrappedNumber
        // TODO; XlaTensor
        torch::lazy::LazyTensorPtr lazy_self = torch::lazy::GetLtcTensorOrCreateForWrappedNumber(self, *common_device);
        
        auto shapes = torch::lazy::compute_shape_abs(self);
        TORCH_INTERNAL_ASSERT(shapes.size() == 1);

        // currently XLA Node, doesn't take lazy::shape
        auto node = torch::lazy::MakeNode<Abs>(lazy_self->GetIrValue(),
                                                                                      std::move(shapes));
        // TODO: plug in bridge::AtenFromXlaTensor
        auto result = torch::lazy::CreateAtenFromLtcTensor(
                torch::lazy::LazyTensor::Create(std::move(node), *common_device));
        return result;
    };

} // namespace torch_xla
```

TODO here 
- [ ] XLA to create a `xla_native_function_include.h` that contains all of the header that `XLANativeFunctions.cpp` would need, this includes `Counter`, `aten_xla_bridge.h` and ...
- [ ] LTC to create a way for XLA to plug in `XLA_FN_COUNTER` macro
- [ ] XLA to integrate to the upstream device and support `GetBackendDevice`
- [ ] XLA to implement `GetLtcTensorOrCreateForWrappedNumber`
- [ ] LTC to provide a way to replace ` torch::lazy::LazyTensorPtr lazy_self` with `torch_xla::XLATensor`
- [ ] Node related change will be discussed in a separate thread
- [ ] LTC to provide a way to plug in `bridge::AtenFromXlaTensor` instead of `torch::lazy::CreateAtenFromLtcTensor`
- [ ] LTC to provide a way to call `first_xla_tensor.CreateFrom()` instead of ` torch::lazy::LazyTensor::Create`

**Comment by JackCaoG** [comment]
Generated `LazyIr.h` currently looks like
```
#pragma once

// This file contains autogenerated LazyTensor IR nodes
#include <ATen/core/Formatting.h>
#include <c10/core/ScalarType.h>
#include <c10/util/Optional.h>
#include <torch/csrc/lazy/core/hash.h>
#include <torch/csrc/lazy/core/ir.h>
#include <torch/csrc/lazy/core/shape.h>
#include <vector>
//TODO, add a general header to also include NodeOutputShape
#include "torch_xla/csrc/ir.h"


namespace torch_xla {
using at::operator<<;

// kNullValue is used to contribute a static hash value any time
// a node has an Optional<Value> input that is nullopt.  It is important
// to differentiate between HASH(nullopt, something) and HASH(something, nullopt),
// and using kNullValue in the hash function in the order of arguments
// serves this purpose.
static const torch::lazy::Value kNullValue = torch::lazy::Value();

class Abs : public Node {
  // plug in a xla::shape computation function
 public:

  // TODO: change Node constructor to take both xla::shape and lazy::shape
  // TODO: codegen to call NODENAMENodeOutputShape, parameter same order
  Abs(const torch::lazy::Value& self, std::vector<Shape>&& shapes)
      : Node(torch::lazy::OpKind(at::aten::abs),
              {self}, std::move(shapes),
              /* num_outputs */ 1,
              torch::lazy::MHash())
        

  {
    
  }

  // TODO WHC: add a lower declartion
  // TODO JACK: move lower function defionation to a separate file
  std::string ToString() const override {
    std::stringstream ss;
    ss << Node::ToString();
    
    return ss.str();
  }

  

  
  

};

} // namespace torch_xla
```
- [ ] XLA to create a general header to include all of the header that needs to be presented in `LazyIr.h`
- [ ] XLA to rename Node to XLANode
- [ ] XLA to update Node constructor to take both xla::shape and lazy::shape
- [ ] LTC to call $(NodeName)OutputShape in constructor, parameter is the same as the constructor
- [ ] LTC to add a Lower declaration (maybe https://github.com/pytorch/pytorch/blob/master/tools/codegen/dest/lazy_ir.py#L219 is enough?)
- [ ] XLA to move lower implementation to a separate file
- [ ] XLA to clean up Clone method

**Comment by JackCaoG** [comment]
I am playing around with the new code gen, with
```
import pathlib
from torchgen.gen_lazy_tensor import run_gen_lazy_tensor
from torchgen.dest.lazy_ir import GenLazyIR

# assuming this file is under pytorch/xla/
torch_root = pathlib.Path(__file__).absolute().parent.parent
aten_path = str(torch_root / "aten" / "src" / "ATen")
shape_inference_hdr_path = str(torch_root / "torch" / "csrc" / "lazy" / "core" / "shape_inference.h")

# TODO: remove `symbolicShapeEnabled` check
run_gen_lazy_tensor(
    aten_path=aten_path,
    source_yaml="xla_native_functions.yaml",
    backend_name="XLA",
    output_dir="torch_xla/csrc/generated",
    dry_run=False,
    impl_path="torch_xla/csrc/aten_xla_type.cpp",
    node_base="Node",
    node_base_hdr="torch_xla/csrc/ir.h",
    build_in_tree=True,
    per_operator_headers=True,
    lazy_ir_generator=GenLazyIR,
    shape_inference_hdr=shape_inference_hdr_path,
    metrics_counter='XLA_FN_COUNTER("xla::")',
    # TODO: move this function to `torch::lazy` namespace
    get_tensor_or_wrap_number="GetXlaTensorOrCreateForWrappedNumber",
    create_tensor="CreateFrom",
    create_from_first_tensor=True,
)
```

I can get 
```
// @generated by torchgen/gen.py from DispatchKeyNativeFunctions.cpp
#include </usr/local/google/home/jackcao/Desktop/gitProj2/pytorch/torch/csrc/lazy/core/shape_inference.h>
#include <ATen/Functions.h>
#include <ATen/MetaFunctions.h>
#include <ATen/Operators.h>
#include <ATen/native/CPUFallback.h>
#include <torch/csrc/lazy/core/lazy_graph_executor.h>
#include <torch/csrc/lazy/core/metrics.h>
#include <torch/csrc/lazy/core/shape.h>
#include <torch/csrc/lazy/core/tensor.h>
#include <torch_xla/csrc/generated/LazyIr.h>
#include <torch_xla/csrc/generated/XLANativeFunctions.h>

namespace torch_xla {

at::Tensor XLANativeFunctions::abs(const at::Tensor& self) {
  XLA_FN_COUNTER("xla::");
  auto common_device = torch::lazy::GetBackendDevice(self);
  TORCH_INTERNAL_ASSERT(common_device);

  torch::lazy::LazyTensorPtr lazy_self =
      torch::lazy::GetXlaTensorOrCreateForWrappedNumber(self, *common_device);

  auto shapes = torch::lazy::compute_shape_abs(self);
  TORCH_INTERNAL_ASSERT(shapes.size() == 1);
  if (symbolicShapeEnabled()) {
    std::vector<jit::IValue> inputs = {self};
    char* schema_str = "aten::abs(Tensor self) -> Tensor";
    applySymbolicShapesOnLT(schema_str, inputs, shapes);
  }

  auto node =
      torch::lazy::MakeNode<Abs>(lazy_self->GetIrValue(), std::move(shapes));
  auto result = torch::lazy::CreateAtenFromLtcTensor(
      self.CreateFrom(std::move(node), *common_device));
  return result;
};

}  // namespace torch_xla
```

I think this is really close to what I need. Next thing to do is to overwrite `GenLazyIR` and have a `GenXLALazyIR`

**Comment by wconstab** [comment]
yea looks good to me.

oh, one thing that i was wondering, RE this point:
> XLA to create a general header to include all of the header that needs to be presented in LazyIr.h

do I need to add another arg for you to pass a new header, or does it work for you to pass one of the existing headers (e.g. the 'node_base' header) as your 'general header' which also includes the node base header itself?

**Comment by JackCaoG** [comment]
@wconstab I think we are really close, I would need some additional changes from the code gen

- [ ] Let XLA to overwrite the `torch::lazy::LazyTensorPtr` to `XlaTensor` or change it `auto`
- [ ] Let XLA to overwrite `bridge_str` since we need `bridge::AtenFromXlaTensor` instead of `torch::lazy::CreateAtenFromLtcTensor`
- [ ] Let XLA to overwrite `torch::lazy::Value` to `torch_xla::XlaVlaue` since we often need to call `Value.xla_shape`

for the first two I do a quick hack
```
--- a/torchgen/dest/lazy_ir.py
+++ b/torchgen/dest/lazy_ir.py
@@ -259,7 +259,8 @@ class GenLazyNativeFuncDefinition:
                     )
                 else:
                     lazy_tensor_decls.append(
-                        f"{self.tensor_class}Ptr lazy_{arg.name} = "
+                        #f"{self.tensor_class}Ptr lazy_{arg.name} = "
+                        f"auto lazy_{arg.name} = "
                         f"{self.backend_namespace}::{self.get_tensor_or_wrap_number}({arg.name}, *common_device);"
                     )
             elif isinstance(arg.lazy_type, OptionalCType):
@@ -346,7 +347,8 @@ class GenLazyNativeFuncDefinition:
         value_types_names = [f"{a.name}" for a in value_args if not a.is_wrapped_scalar]
         assert len(value_types_names) > 0, "Code below assumes there is at least one tensor arg"
         first_tensor_name = value_types_names[0]
-        bridge_str = f"""auto result = torch::lazy::CreateAtenFromLtcTensor(
+        #bridge_str = f"""auto result = torch::lazy::CreateAtenFromLtcTensor(
+        bridge_str = f"""auto result = bridge::AtenFromXlaTensor("""
                 {self.create_lazy_tensor(first_tensor_name)}(std::move(node), *common_device));"""
 
         if returns_length > 1:

```

which seems to produce the correct result.

On my end I still need to 
- [ ] remove `torch_xla::ir` namespace
- [ ] remove `torch_xla::ir::ops` namespace
- [ ] reorder `XlaNode` constructor to take `xka_shape_fn` before `operands`
- [ ] create a .h to include all `{NodeName}OutputShape`
- [ ] create a .cpp to include all `{NodeName}::Lower` implementation

generated ir files now looks like
```
#pragma once

// This file contains autogenerated LazyTensor IR nodes
#include <ATen/core/Formatting.h>
#include <c10/core/ScalarType.h>
#include <c10/util/Optional.h>
#include <torch/csrc/lazy/core/hash.h>
#include <torch/csrc/lazy/core/ir.h>
#include <torch/csrc/lazy/core/shape.h>

#include <vector>

#include "torch_xla/csrc/generated_file_include.h"

namespace torch_xla {
using at::operator<<;

// kNullValue is used to contribute a static hash value any time
// a node has an Optional<Value> input that is nullopt.  It is important
// to differentiate between HASH(nullopt, something) and HASH(something,
// nullopt), and using kNullValue in the hash function in the order of arguments
// serves this purpose.
static const torch::lazy::Value kNullValue = torch::lazy::Value();

class Abs : public Node {
 public:
  Abs(const torch::lazy::Value& self, std::vector<Shape>&& shapes)
      : Node(
            torch::lazy::OpKind(at::aten::abs),
            [&]() { return AbsOutputShape(self); }, {self}, std::move(shapes),
            /* num_outputs */ 1, torch::lazy::MHash())

  {}

  std::string ToString() const override {
    std::stringstream ss;
    ss << Node::ToString();

    return ss.str();
  }

  torch_xla::XlaOpVector Lower(LoweringContext* loctx) const override;
};

}  // namespace torch_xla
```

**Comment by JackCaoG** [comment]
Fixing last couple build issue related to `abs` op is being used in other lowering, WIP pr in https://github.com/pytorch/xla/pull/3544.
