### ISSUE TITLE
[Functionalization] Lower *view*_scatter ops properly

### ISSUE THREAD

**Issue by alanwaketan** [pytorch/xla#4767]
All scatter ops are written in a way that reuses our view infrastructure, and we need to convert them into proper scatter ops that are without the view infrastructure. Looks like we can directly apply *View*Update ops listed [here](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/view.cpp#L66) to do a 1:1 mapping. Jiewen tried AsStridedViewUpdate and [it](https://paste.googleplex.com/5183911360462848) passed TestViewOpsXLA.test_as_strided_inplace_view_xla and TestViewOpsXLA.test_as_strided_view_xla tests.
- [x] as_strided_scatter (@alanwaketan, #4770)
- [x] diagonal_scatter (@alanwaketan, #4784)
- [x] select_scatter (@wonjoolee95, #4793)
- [x] slice_scatter (@alanwaketan, #4791)

**Comment by alanwaketan** [comment]
Close this issue as all tasks are completed.
