### ISSUE TITLE
[API Usability] Internalize `parse_xla_device`

### ISSUE THREAD

**Issue by zpcore** [pytorch/xla#7652]
### Clean up torch_xla.core.xla_model.

Internalize `parse_xla_device`.

```[tasklist]
### Tasks
- [ ] Clean up and use upstream torch.distributed.
- [ ] Update the PyTorch/XLA documentation.
- [ ] Update test examples.
```
