### ISSUE TITLE
[API Usability] Delete `check_view_sharing`

### ISSUE THREAD

**Issue by zpcore** [pytorch/xla#7662]
### Clean up torch_xla.core.xla_model.

Delete `check_view_sharing`.

```[tasklist]
### Tasks
- [ ] Delete the API.
- [ ] Update the PyTorch/XLA documentation.
- [ ] Update test examples.
```
