### ISSUE TITLE
[API Usability] Internalize `reduce_gradients`

### ISSUE THREAD

**Issue by zpcore** [pytorch/xla#7663]
### Clean up torch_xla.core.xla_model.

Only used by optimizer_step

```[tasklist]
### Tasks
- [ ] Internalize the API.
- [ ] Update the PyTorch/XLA documentation.
- [ ] Update test examples.
```
